config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  get 'dashboard/show'

  get 'sessions/new'
  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'dashboard#show'
  post   'dashboard'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'
  root 'dashboard#show'

  resources :orcamentos
  resources :fornecedors
  resources :servicos
  resources :estoques
  resources :veiculos

end

app/models/estoque.rb
class Estoque < ActiveRecord::Base
end

app/controllers/estoques_controller.rb
class EstoquesController < ApplicationController
  before_action :set_estoque, only: [:show, :edit, :update, :destroy]

  # GET /estoques
  # GET /estoques.json
  def index
    if params[:search]
      @estoques = Estoque.where("titulo like ?","%#{ params[:search]}%")
    else
      @estoques = Estoque.all
    end
  end

  # GET /estoques/1
  # GET /estoques/1.json
  def show
  end

  # GET /estoques/new
  def new
    @estoque = Estoque.new
  end

  # GET /estoques/1/edit
  def edit
  end

  # POST /estoques
  # POST /estoques.json
  def create
    @estoque = Estoque.new(estoque_params)

    respond_to do |format|
      if @estoque.save
        format.html { redirect_to @estoque, notice: 'Estoque was successfully created.' }
        format.json { render :show, status: :created, location: @estoque }
      else
        format.html { render :new }
        format.json { render json: @estoque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estoques/1
  # PATCH/PUT /estoques/1.json
  def update
    respond_to do |format|
      if @estoque.update(estoque_params)
        format.html { redirect_to @estoque, notice: 'Estoque was successfully updated.' }
        format.json { render :show, status: :ok, location: @estoque }
      else
        format.html { render :edit }
        format.json { render json: @estoque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estoques/1
  # DELETE /estoques/1.json
  def destroy
    @estoque.destroy
    respond_to do |format|
      format.html { redirect_to estoques_url, notice: 'Estoque was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estoque
      @estoque = Estoque.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estoque_params
      params.require(:estoque).permit(:titulo, :estoque, :valorCusto, :valorVenda)
    end
end

app/helpers/estoques_helper.rb
module EstoquesHelper
end

app/views/estoques/_form.html.erb
<%= form_for @estoque, :html => { :class => "form-horizontal estoque" } do |f| %>

    <% if @estoque.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@estoque.errors.count, "error") %> prohibited this estoque from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @estoque.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :titulo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :titulo, :class => 'form-control' %>
    </div>
    <%= error_span(@estoque[:titulo]) %>
  </div>
  <div class="control-group">
    <%= f.label :estoque, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :estoque, :class => 'form-control' %>
    </div>
    <%= error_span(@estoque[:estoque]) %>
  </div>
  <div class="control-group">
    <%= f.label :valorCusto, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :valorCusto, :class => 'form-control' %>
    </div>
    <%= error_span(@estoque[:valorCusto]) %>
  </div>
  <div class="control-group">
    <%= f.label :valorVenda, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :valorVenda, :class => 'form-control' %>
    </div>
    <%= error_span(@estoque[:valorVenda]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            estoques_path, :class => 'btn btn-default' %>

<% end %>

app/views/estoques/edit.html.erb
<%- model_class = Estoque -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/estoques/index.html.erb
<%- model_class = Estoque -%>

<div class="page-header">
  <%= form_tag(estoques_path, :method => :get) do %>
      <%= text_field_tag 'search', nil, placeholder: 'Entre com o titulo...'%>
      <%= submit_tag "Pesquisar"%>
  <% end %>
  <a href="/estoques#index">
    <%= button_tag "Limpar pesquisa" %>
  </a>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>

</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:estoque) %></th>
      <th><%= model_class.human_attribute_name(:valorCusto) %></th>
      <th><%= model_class.human_attribute_name(:valorVenda) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @estoques.each do |estoque| %>
      <tr>
        <td><%= link_to estoque.id, estoque_path(estoque) %></td>
        <td><%= estoque.titulo %></td>
        <td><%= estoque.estoque %></td>
        <td><%= estoque.valorCusto %></td>
        <td><%= estoque.valorVenda %></td>
        <td><%=l estoque.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_estoque_path(estoque), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      estoque_path(estoque),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_estoque_path,
            :class => 'btn btn-primary' %>

app/views/estoques/new.html.erb
<%- model_class = Estoque -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/estoques/show.html.erb
<%- model_class = Estoque -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @estoque.titulo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:estoque) %>:</strong></dt>
  <dd><%= @estoque.estoque %></dd>
  <dt><strong><%= model_class.human_attribute_name(:valorCusto) %>:</strong></dt>
  <dd><%= @estoque.valorCusto %></dd>
  <dt><strong><%= model_class.human_attribute_name(:valorVenda) %>:</strong></dt>
  <dd><%= @estoque.valorVenda %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              estoques_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_estoque_path(@estoque), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              estoque_path(@estoque),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>