config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  get 'dashboard/show'

  get 'sessions/new'
  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'dashboard#show'
  post   'dashboard'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'
  root 'dashboard#show'

  resources :orcamentos
  resources :fornecedors
  resources :servicos
  resources :estoques
  resources :veiculos

end

app/models/fornecedor.rb
class Fornecedor < ActiveRecord::Base
end

app/controllers/fornecedors_controller.rb
class FornecedorsController < ApplicationController
  before_action :set_fornecedor, only: [:show, :edit, :update, :destroy]

  # GET /fornecedors
  # GET /fornecedors.json
  def index
    if params[:search]
      @fornecedors = Fornecedor.where("empresa like ?","%#{ params[:search]}%")
    else
      @fornecedors = Fornecedor.all
    end
  end

  # GET /fornecedors/1
  # GET /fornecedors/1.json
  def show
  end

  # GET /fornecedors/new
  def new
    @fornecedor = Fornecedor.new
  end

  # GET /fornecedors/1/edit
  def edit
  end

  # POST /fornecedors
  # POST /fornecedors.json
  def create
    @fornecedor = Fornecedor.new(fornecedor_params)

    respond_to do |format|
      if @fornecedor.save
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully created.' }
        format.json { render :show, status: :created, location: @fornecedor }
      else
        format.html { render :new }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fornecedors/1
  # PATCH/PUT /fornecedors/1.json
  def update
    respond_to do |format|
      if @fornecedor.update(fornecedor_params)
        format.html { redirect_to @fornecedor, notice: 'Fornecedor was successfully updated.' }
        format.json { render :show, status: :ok, location: @fornecedor }
      else
        format.html { render :edit }
        format.json { render json: @fornecedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fornecedors/1
  # DELETE /fornecedors/1.json
  def destroy
    @fornecedor.destroy
    respond_to do |format|
      format.html { redirect_to fornecedors_url, notice: 'Fornecedor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fornecedor
      @fornecedor = Fornecedor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fornecedor_params
      params.require(:fornecedor).permit(:empresa, :contato, :telefone, :observacoes)
    end
end

app/helpers/fornecedors_helper.rb
module FornecedorsHelper
end

app/views/fornecedors/_form.html.erb
<%= form_for @fornecedor, :html => { :class => "form-horizontal fornecedor" } do |f| %>

    <% if @fornecedor.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@fornecedor.errors.count, "error") %> prohibited this fornecedor from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @fornecedor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :empresa, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :empresa, :class => 'form-control' %>
    </div>
    <%= error_span(@fornecedor[:empresa]) %>
  </div>
  <div class="control-group">
    <%= f.label :contato, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :contato, :class => 'form-control' %>
    </div>
    <%= error_span(@fornecedor[:contato]) %>
  </div>
  <div class="control-group">
    <%= f.label :telefone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%= error_span(@fornecedor[:telefone]) %>
  </div>
  <div class="control-group">
    <%= f.label :observacoes, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :observacoes, :class => 'form-control' %>
    </div>
    <%= error_span(@fornecedor[:observacoes]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            fornecedors_path, :class => 'btn btn-default' %>

<% end %>

app/views/fornecedors/edit.html.erb
<%- model_class = Fornecedor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fornecedors/index.html.erb
<%- model_class = Fornecedor -%>

<div class="page-header">
  <%= form_tag(fornecedors_path, :method => :get) do %>
      <%= text_field_tag 'search', nil, placeholder: 'Entre com a empresa...'%>
      <%= submit_tag "Pesquisar"%>
  <% end %>
  <a href="/fornecedors#index">
    <%= button_tag "Limpar pesquisa" %>
  </a>
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:empresa) %></th>
      <th><%= model_class.human_attribute_name(:contato) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%= model_class.human_attribute_name(:observacoes) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fornecedors.each do |fornecedor| %>
      <tr>
        <td><%= link_to fornecedor.id, fornecedor_path(fornecedor) %></td>
        <td><%= fornecedor.empresa %></td>
        <td><%= fornecedor.contato %></td>
        <td><%= fornecedor.telefone %></td>
        <td><%= fornecedor.observacoes %></td>
        <td><%=l fornecedor.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_fornecedor_path(fornecedor), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      fornecedor_path(fornecedor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_fornecedor_path,
            :class => 'btn btn-primary' %>

app/views/fornecedors/new.html.erb
<%- model_class = Fornecedor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fornecedors/show.html.erb
<%- model_class = Fornecedor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:empresa) %>:</strong></dt>
  <dd><%= @fornecedor.empresa %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contato) %>:</strong></dt>
  <dd><%= @fornecedor.contato %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @fornecedor.telefone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:observacoes) %>:</strong></dt>
  <dd><%= @fornecedor.observacoes %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              fornecedors_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_fornecedor_path(@fornecedor), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              fornecedor_path(@fornecedor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>