config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  get 'dashboard/show'

  get 'sessions/new'
  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'dashboard#show'
  post   'dashboard'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'
  root 'dashboard#show'

  resources :orcamentos
  resources :fornecedors
  resources :servicos
  resources :estoques
  resources :veiculos

end

app/models/servico.rb
class Servico < ActiveRecord::Base
end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController
  before_action :set_servico, only: [:show, :edit, :update, :destroy]

  # GET /servicos
  # GET /servicos.json
  def index
    if params[:search]
      @servicos = Servico.where("titulo like ?","%#{ params[:search]}%")
    else
      @servicos = Servico.all
    end
  end

  # GET /servicos/1
  # GET /servicos/1.json
  def show
  end

  # GET /servicos/new
  def new
    @servico = Servico.new
  end

  # GET /servicos/1/edit
  def edit
  end

  # POST /servicos
  # POST /servicos.json
  def create
    @servico = Servico.new(servico_params)

    respond_to do |format|
      if @servico.save
        format.html { redirect_to @servico, notice: 'Servico was successfully created.' }
        format.json { render :show, status: :created, location: @servico }
      else
        format.html { render :new }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicos/1
  # PATCH/PUT /servicos/1.json
  def update
    respond_to do |format|
      if @servico.update(servico_params)
        format.html { redirect_to @servico, notice: 'Servico was successfully updated.' }
        format.json { render :show, status: :ok, location: @servico }
      else
        format.html { render :edit }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicos/1
  # DELETE /servicos/1.json
  def destroy
    @servico.destroy
    respond_to do |format|
      format.html { redirect_to servicos_url, notice: 'Servico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servico
      @servico = Servico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servico_params
      params.require(:servico).permit(:titulo, :valorVenda)
    end
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/views/servicos/_form.html.erb
<%= form_for @servico, :html => { :class => "form-horizontal servico" } do |f| %>

    <% if @servico.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@servico.errors.count, "error") %> prohibited this servico from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @servico.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :titulo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :titulo, :class => 'form-control' %>
    </div>
    <%= error_span(@servico[:titulo]) %>
  </div>
  <div class="control-group">
    <%= f.label :valorVenda, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :valorVenda, :class => 'form-control' %>
    </div>
    <%= error_span(@servico[:valorVenda]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            servicos_path, :class => 'btn btn-default' %>

<% end %>

app/views/servicos/edit.html.erb
<%- model_class = Servico -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/servicos/index.html.erb
<%- model_class = Servico -%>

<div class="page-header">
  <%= form_tag(servicos_path, :method => :get) do %>
      <%= text_field_tag 'search', nil, placeholder: 'Entre com o titulo...'%>
      <%= submit_tag "Pesquisar"%>
  <% end %>
  <a href="/servicos#index">
    <%= button_tag "Limpar pesquisa" %>
  </a>

  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:valorVenda) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @servicos.each do |servico| %>
      <tr>
        <td><%= link_to servico.id, servico_path(servico) %></td>
        <td><%= servico.titulo %></td>
        <td><%= servico.valorVenda %></td>
        <td><%=l servico.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_servico_path(servico), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      servico_path(servico),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_servico_path,
            :class => 'btn btn-primary' %>

app/views/servicos/new.html.erb
<%- model_class = Servico -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/servicos/show.html.erb
<%- model_class = Servico -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titulo) %>:</strong></dt>
  <dd><%= @servico.titulo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:valorVenda) %>:</strong></dt>
  <dd><%= @servico.valorVenda %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              servicos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_servico_path(@servico), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              servico_path(@servico),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>