config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  get 'dashboard/show'

  get 'sessions/new'
  get    'signup'  => 'usuarios#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'dashboard#show'
  post   'dashboard'   => 'sessions#new'
  delete 'logout'  => 'sessions#destroy'
  root 'dashboard#show'

  resources :orcamentos
  resources :fornecedors
  resources :servicos
  resources :estoques
  resources :veiculos

end

app/models/veiculo.rb
class Veiculo < ActiveRecord::Base
end

app/controllers/veiculos_controller.rb
class VeiculosController < ApplicationController
  before_action :set_veiculo, only: [:show, :edit, :update, :destroy]

  # GET /veiculos
  # GET /veiculos.json
  def index
    if params[:search]
      @veiculos = Veiculo.where("placa like ?","%#{ params[:search]}%")
    else
      @veiculos = Veiculo.all
    end
  end

  # GET /veiculos/1
  # GET /veiculos/1.json
  def show
  end

  # GET /veiculos/new
  def new
    @veiculo = Veiculo.new
  end

  # GET /veiculos/1/edit
  def edit
  end

  # POST /veiculos
  # POST /veiculos.json
  def create
    @veiculo = Veiculo.new(veiculo_params)

    respond_to do |format|
      if @veiculo.save
        format.html { redirect_to @veiculo, notice: 'Veiculo was successfully created.' }
        format.json { render :show, status: :created, location: @veiculo }
      else
        format.html { render :new }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veiculos/1
  # PATCH/PUT /veiculos/1.json
  def update
    respond_to do |format|
      if @veiculo.update(veiculo_params)
        format.html { redirect_to @veiculo, notice: 'Veiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @veiculo }
      else
        format.html { render :edit }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veiculos/1
  # DELETE /veiculos/1.json
  def destroy
    @veiculo.destroy
    respond_to do |format|
      format.html { redirect_to veiculos_url, notice: 'Veiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veiculo
      @veiculo = Veiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veiculo_params
      params.require(:veiculo).permit(:placa, :modelo, :ano, :contato, :telefone)
    end
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/veiculos/_form.html.erb
<%= form_for @veiculo, :html => { :class => "form-horizontal veiculo" } do |f| %>

    <% if @veiculo.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@veiculo.errors.count, "error") %> prohibited this veiculo from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @veiculo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :placa, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :placa, :class => 'form-control' %>
    </div>
    <%= error_span(@veiculo[:placa]) %>
  </div>
  <div class="control-group">
    <%= f.label :modelo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :modelo, :class => 'form-control' %>
    </div>
    <%= error_span(@veiculo[:modelo]) %>
  </div>
  <div class="control-group">
    <%= f.label :ano, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :ano, :class => 'form-control' %>
    </div>
    <%= error_span(@veiculo[:ano]) %>
  </div>
  <div class="control-group">
    <%= f.label :contato, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :contato, :class => 'form-control' %>
    </div>
    <%= error_span(@veiculo[:contato]) %>
  </div>
  <div class="control-group">
    <%= f.label :telefone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%= error_span(@veiculo[:telefone]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            veiculos_path, :class => 'btn btn-default' %>

<% end %>

app/views/veiculos/edit.html.erb
<%- model_class = Veiculo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/veiculos/index.html.erb
<%- model_class = Veiculo -%>

<div class="page-header">
  <%= form_tag(veiculos_path, :method => :get) do %>
      <%= text_field_tag 'search', nil, placeholder: 'Entre com a placa...'%>
      <%= submit_tag "Pesquisar"%>
  <% end %>
  <a href="/veiculos#index">
    <%= button_tag "Limpar pesquisa" %>
  </a>

  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:placa) %></th>
      <th><%= model_class.human_attribute_name(:modelo) %></th>
      <th><%= model_class.human_attribute_name(:ano) %></th>
      <th><%= model_class.human_attribute_name(:contato) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @veiculos.each do |veiculo| %>
      <tr>
        <td><%= link_to veiculo.id, veiculo_path(veiculo) %></td>
        <td><%= veiculo.placa %></td>
        <td><%= veiculo.modelo %></td>
        <td><%= veiculo.ano %></td>
        <td><%= veiculo.contato %></td>
        <td><%= veiculo.telefone %></td>
        <td><%=l veiculo.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_veiculo_path(veiculo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      veiculo_path(veiculo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_veiculo_path,
            :class => 'btn btn-primary' %>

app/views/veiculos/new.html.erb
<%- model_class = Veiculo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/veiculos/show.html.erb
<%- model_class = Veiculo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:placa) %>:</strong></dt>
  <dd><%= @veiculo.placa %></dd>
  <dt><strong><%= model_class.human_attribute_name(:modelo) %>:</strong></dt>
  <dd><%= @veiculo.modelo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ano) %>:</strong></dt>
  <dd><%= @veiculo.ano %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contato) %>:</strong></dt>
  <dd><%= @veiculo.contato %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @veiculo.telefone %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              veiculos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_veiculo_path(@veiculo), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              veiculo_path(@veiculo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>